### ISSUE TITLE
Is this up to date as of September 2016?

### ISSUE THREAD

**Issue by joemccann** [sindresorhus/github-markdown-css#33]
Seeing last update was 9 months ago, but I believe GitHub changed their font.

**Comment by sindresorhus** [comment]
Yes, the GitHub font change is already part of the latest release, 2.4.0. See: https://github.com/sindresorhus/github-markdown-css/issues/30

The CSS is generated. I just ran the script now, and not many changes since then: https://github.com/sindresorhus/github-markdown-css/commit/016093225b6d4f324fa10bd91332c8cf19bcd019

**Comment by joemccann** [comment]
great thanks!

**Comment by joemccann** [comment]
I'm using this on

dillinger.io

**Comment by sindresorhus** [comment]
That's awesome! I've used dillinger before, it's great :)

**Comment by joemccann** [comment]
thanks!
