### ISSUE TITLE
how to change theme

### ISSUE THREAD

**Issue by HaofangLiu** [sindresorhus/github-markdown-css#99]
Hi I added to my vue3 project by yarn, and import in main.ts file `import "github-markdown-css"`

also add style to global index.scss ,

the stye can show in default theme, but I try to switch light theme, 

tyied `import "github-markdown-light.css"` or `<link rel="stylesheet" href="github-markdown.css">` but both are wrong as cannot find the file.

Did I miss something? how can I switch to light theme?

**Comment by hyrious** [comment]
1. To import a file in some package, generally import from "{package-name}/{path-to-that-file}".

   ```js
   import 'github-markdown-css/github-markdown-light.css'
   ```

   Some old webpack template may define an alias from "~pkgname/..." to the real file, I hope you do not use that.

2. It is not obvious to implement switching between css files, you have to know what really happens when you write down the import statement. Generally people have two expected result: a. styles are bundled to another file and added to the result page as a `<link>`, b. styles are transformed to string and then be injected to a `<style>` tag in the runtime.

    Sadly, none of the two behaviors will support switching files without additional treatment. You may have a look at some existing sites which implemented switching themes to know how they do.
